name: Release Export (HTML5)

on:
  push:
    tags:
      - "release-*"
    branches:
      - main

jobs:
  export-html5:
    name: Export HTML5 Build
    runs-on: ubuntu-latest

    steps:
      # -----------------------
      # Checkout do repositório
      # -----------------------
      - name: Checkout repository
        uses: actions/checkout@v4

      # -----------------------
      # Download Godot Headless + templates
      # -----------------------
      - name: Download Godot 4.4.stable Headless + Templates
        run: |
          GODOT_VERSION="4.4-stable"
          wget https://github.com/godotengine/godot/releases/download/${GODOT_VERSION}/Godot_v${GODOT_VERSION}_linux.x86_64.zip -O godot_headless.zip
          wget  https://github.com/godotengine/godot/releases/download/${GODOT_VERSION}/Godot_v${GODOT_VERSION}_export_templates.tpz -O templates.tpz
      # -----------------------
      # Instalar Godot Headless
      # -----------------------
      - name: Install Godot
        run: |
          mkdir -p $HOME/godot
          unzip godot_headless.zip -d $HOME/godot
          ls -al $HOME/godot/Godot_v4.4-stable_linux.x86_64
          mv $HOME/godot/Godot_v4.4-stable_linux.x86_64 $HOME/godot/godot

      # -----------------------
      # Instalar Export Templates
      # -----------------------
      - name: Install Export Templates
        run: |
          mkdir -p ~/.local/share/godot/export_templates/4.4.stable
          unzip -j templates.tpz -d ~/.local/share/godot/export_templates/4.4.stable
          ls -al ~/.local/share/godot/export_templates/4.4.stable

      # -----------------------
      # Executar Export HTML5
      # -----------------------
      - name: Export HTML5
        run: |
          mkdir -p build/html5
          $HOME/godot/godot --headless --verbose \
            --export-release "HTML5" build/html5/index.html

      # -----------------------
      # Publicar artefato
      # -----------------------
      - name: Upload HTML5 artifact
        uses: actions/upload-artifact@v4
        with:
          name: html5-export
          path: build/html5
